# Generated by Django 4.0.4 on 2022-05-20 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
            ],
        ),
    ]
