# Generated by Django 4.0.4 on 2022-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='commentid',
            field=models.IntegerField(null=True),
        ),
    ]
